### ISSUE TITLE
Error converting to pdf caused by croatian-specific letter in a section title (ž)

### ISSUE THREAD

**Issue by greguric** [asciidoc-py/asciidoc-py2#109]
Hi, I encountered a problem while trying to export asciidoc formated txt file to pdf. The problem is caused when I use a letter "ž" in a section title. The error I get is:

a2x: ERROR: "dblatex" -t pdf -p "/etc/asciidoc/dblatex/asciidoc-dblatex.xsl" -s "/etc/asciidoc/dblatex/asciidoc-dblatex.sty"   "/home/marko/Brackets/ibes_2016_peteh_greguric.xml" returned non-zero exit status 1

Is it a bug or am I just missing something? The thing is that the same letter doesn't make any problem anywhere else in the text.

**Comment by elextr** [comment]
Try `a2x -v` to see if dblatex gives a more useful error message.

**Comment by greguric** [comment]
Sorry for me not responding for 3 days. I did as you suggested and here's what I got:

`marko@dell:~/Brackets$
a2x -vf pdf ibes_2016_peteh_greguric.txt 
a2x: args: ['-vf', 'pdf', 'ibes_2016_peteh_greguric.txt']
a2x: resource files: []
a2x: resource directories: ['/etc/asciidoc/images', '/etc/asciidoc/stylesheets']
a2x: executing: "/usr/bin/asciidoc" --backend docbook -a "a2x-format=pdf"  --verbose  --out-file "/home/marko/Brackets/ibes_2016_peteh_greguric.xml" "/home/marko/Brackets/ibes_2016_peteh_greguric.txt"

asciidoc: reading: /etc/asciidoc/asciidoc.conf
asciidoc: reading: /etc/asciidoc/asciidoc.conf
asciidoc: reading: /home/marko/Brackets/ibes_2016_peteh_greguric.txt
asciidoc: reading: /etc/asciidoc/docbook45.conf
asciidoc: reading: /etc/asciidoc/filters/source/source-highlight-filter.conf
asciidoc: reading: /etc/asciidoc/filters/music/music-filter.conf
asciidoc: reading: /etc/asciidoc/filters/code/code-filter.conf
asciidoc: reading: /etc/asciidoc/filters/graphviz/graphviz-filter.conf
asciidoc: reading: /etc/asciidoc/filters/latex/latex-filter.conf
asciidoc: reading: /etc/asciidoc/lang-en.conf
asciidoc: writing: /home/marko/Brackets/ibes_2016_peteh_greguric.xml

a2x: executing: "xmllint" --nonet --noout --valid "/home/marko/Brackets/ibes_2016_peteh_greguric.xml"


a2x: executing: "dblatex" -t pdf -p "/etc/asciidoc/dblatex/asciidoc-dblatex.xsl" -s "/etc/asciidoc/dblatex/asciidoc-dblatex.sty"  -V  "/home/marko/Brackets/ibes_2016_peteh_greguric.xml"

Build the book set list...
xsltproc -o /tmp/tmpcHIKuG/doclist.txt --xinclude --xincludestyle doclist.xsl /home/marko/Brackets/ibes_2016_peteh_greguric.xml
Build the listings...
xsltproc -o /tmp/tmpcHIKuG/listings.xml --xinclude --xincludestyle --param current.dir '/home/marko/Brackets' /usr/share/dblatex/xsl/common/mklistings.xsl /home/marko/Brackets/ibes_2016_peteh_greguric.xml
xsltproc -o ibes_2016_peteh_greguric.rtex --xinclude --xincludestyle --param current.dir '/home/marko/Brackets' --param listings.xml '/tmp/tmpcHIKuG/listings.xml' /tmp/tmpcHIKuG/custom.xsl /home/marko/Brackets/ibes_2016_peteh_greguric.xml
XSLT stylesheets DocBook - LaTeX 2e (0.3.4-2)

Image 'dblatex' not found
Build ibes_2016_peteh_greguric.pdf
built-in module pdftex registered
no support found for ifthen
no support found for ifxetex
no support found for fontspec
no support found for xltxtra
no support found for fontenc
no support found for inputenc
no support found for fancybox
built-in module makeidx registered
no support found for asciidoc-dblatex
building additional files...
checking if compiling is necessary...
the output file doesn't exist
pdflatex -interaction=batchmode ibes_2016_peteh_greguric.tex
pdflatex failed
ibes_2016_peteh_greguric.aux:23: Missing \endcsname inserted.
ibes_2016_peteh_greguric.aux:23: leading text: ...{{1}{1}{Sa\v {z}etak\relax }{section.1}{}}
Unexpected error occured
Error: pdflatex compilation failed

a2x: ERROR: "dblatex" -t pdf -p "/etc/asciidoc/dblatex/asciidoc-dblatex.xsl" -s "/etc/asciidoc/dblatex/asciidoc-dblatex.sty"  -V  "/home/marko/Brackets/ibes_2016_peteh_greguric.xml" returned non-zero exit status 1 
`

It only happens if I put the word that contains a letter "ž" e.g. "sažetak" and mark it as level 1 heading. So if I put it like this:
`= Sažetak =` than it turns out ok.

But if I put the same word like this:
`== Sažetak ==`

I get error.

Thanks for the time and any advice :)
Marko

**Comment by elextr** [comment]
This appears to be a problem inside dblatex, not Asciidoc.  Try to make the smallest file where the problem occurs, then save the docbook by adding the -k option to a2x to keep the docbook (.xml) file and report to dblatex with the .xml docbook file.

**Comment by greguric** [comment]
Tnx! Will do that!
