### ISSUE TITLE
images from weblinks have wide margin with their caption 

### ISSUE THREAD

**Issue by seinecle** [asciidoc-py/asciidoc-py2#110]
To reproduce:

```
== initial view

image::en/project-initial-view.png[align="center", title="initial view when opening a graph"]

This is how the network appears in Gephi. Not very useful! Let's examine what we have here.

== basic view of Gephi's interface

image::https://docs.google.com/drawings/d/1MVPuD8fYe8bEJJJ67heQjrMidA7vyizGc37p4y5LRH8/pub?w=960[align="center", title="the 3 main screens in Gephi"]

```

In the first image (project-initial-view.png), the caption that follows is almost touching the pic. But in the second image, there is a wide margin (the equivalent of 2 line breaks) between the image and the caption. 

This is visible in asciidoc preview, html conversion and pdf conversion (but not in revealjs).

To see live versions of these documents: navigate to the bottom of this page, section "Simple project from a to z": https://seinecle.github.io/gephi-tutorials/

**Comment by elextr** [comment]
This is the repository for the original Python Asciidoc implementation.

Github.io uses the Asciidoctor implementation of Asciidoc [here](https://github.com/asciidoctor).  Although they also watch this repo its probably best to raise the issue there.

**Comment by seinecle** [comment]
Thanks. False alert, the margin issue was due to the way I handled Google drawing files.
