### ISSUE TITLE
With -e option: asciidoc: ERROR: [attributes] missing 'attributelist-pattern' entry

### ISSUE THREAD

**Issue by eepp** [asciidoc-py/asciidoc-py2#111]
Using `asciidoc 8.6.9`, with the `-e` option (no implicit configuration file), I get this:

```
asciidoc: ERROR: [attributes] missing 'attributelist-pattern' entry
asciidoc: FAILED: unexpected error:
asciidoc: ------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/bin/asciidoc", line 5940, in asciidoc
    AttributeList.initialize()
  File "/usr/bin/asciidoc", line 1923, in initialize
    AttributeList.pattern = document.attributes['attributelist-pattern']
  File "/usr/bin/asciidoc", line 115, in __getitem__
    return dict.__getitem__(self, key.lower())
KeyError: 'attributelist-pattern'

```

**Comment by elextr** [comment]
As the message says, since you didn't load the configuration, you don't have an `attributelist-pattern` defined.

**Comment by eepp** [comment]
Ok I was under the impression that only the implicit `asciidoc.conf` in the local directory is not loaded. How do you _not_ load this one, but load the other default ones?

**Comment by elextr** [comment]
The only way is to change its name and then use `-f` to explicitly load it when you want to.
