### ISSUE TITLE
Any chance asciidoc can support outputting to mdoc?

### ISSUE THREAD

**Issue by pouar** [asciidoc-py/asciidoc-py2#117]
Or is it not worth supporting due to the asciidoc format being the human readable source format and not the man pages it generates?

**Comment by elextr** [comment]
I'm not sure what the point of generating mdoc is, its certainly NOT a human readable format and Asciidoc generates man pages as you say :)

But if someone had a use case to generate mdoc they can probably modify the manpage configuration themselves, but its unlikely to be included in Asciidoc.

**Comment by pouar** [comment]
The only advantage the mdoc format seems to have over the man format that would be relevant to asciidoc would be easier implementation of semantic searches on man implementations that actually support it (not sure if this is enough to warrant supporting mdoc though). All the other advantages of the mdoc format over the man format asciidoc already has.

**Comment by aerostitch** [comment]
Hi,

The python 2 implementation of asciidoc (which is what this repo is about) is deprecated.
Please move your issue to the python 3 implementation at https://github.com/asciidoc/asciidoc-py3 if still relevant on that newer implementation and close this issue.

Thanks for your help,
Joseph

**Comment by MasterOdin** [comment]
Unlikely to happen anytime soon, and have not heard a huge demand. Closing this and as indicated, above re-open in the other repo if there's interest in it.
