### ISSUE TITLE
Use python2 to invoke a2x

### ISSUE THREAD

**Issue by tureba** [asciidoc-py/asciidoc-py2#118]
Since a2x.py still only works on python2 and since many distributions are pointing python to python3 by default these days, it is becoming ever more important to follow the PEP 394 recommendation (5th bullet point [1]) that says all python invocations of code that is not compatible with 2 and 3 should use the numbered interpreter name. That is not restricted to shebangs, but also includes Makefiles or any shell script.

So this 'python' should be 'python2':
https://github.com/asciidoc/asciidoc/blob/b9b8fca929276b2740b0de0a9143bec17a517105/Makefile.in#L110

[1] https://www.python.org/dev/peps/pep-0394/

**Comment by elextr** [comment]
Ok, fixed.
