### ISSUE TITLE
level rather than level-offset

### ISSUE THREAD

**Issue by Buzzardo** [asciidoc-py/asciidoc-py2#119]
I have a feature request.

I'm the technical writer for open source Spring. We use Asciidoc for our docs (we're driving out the remaining remnants of Docbook and will be all Asciidoc soon). I have some documents that include many (30+) other documents. By using leveloffset, I can include them at whatever level. The trouble is that I have to open each one to see what its original level is and then figure out its offset. If I could have a level attribute that basically says, "No matter what it is in its own file, it's level n here", I could save the trouble of opening the files and figuring out an offset. In other words, a level (rather than leveloffset) attribute would save us time and further encourage re-use (something I'm really pushing for).

Thanks for listening.

**Comment by elextr** [comment]
The intended use-case for `leveloffset` was to allow files representing parts of the document to be marked up as top level files so they can be processed on their own during writing, but can be moved (ie "offset") to a position they need to be in the final document.   

Under that scheme you always know that your included documents are level one so they can be processed on their own, and so `leveloffset` was always simply the level of section it is being included into and you would not need the absolute version you propose.

So just make all include-able documents top level and its easy.

**Comment by Buzzardo** [comment]
Not all of our documents are top-level. The idea behind arbitrarily setting the level rather than setting an offset is that we won't have to go look to see which level it is.

**Comment by elextr** [comment]
Note that "level" is an existing attribute name, maybe "atlevel" or similar.

**Comment by aerostitch** [comment]
Hi,

The python 2 implementation of asciidoc (which is what this repo is about) is deprecated.
Please move your issue to the python 3 implementation at https://github.com/asciidoc/asciidoc-py3 if still relevant on that newer implementation and close this issue.

Thanks for your help,
Joseph

**Comment by MasterOdin** [comment]
Closing for allowing relative offsets as described by https://github.com/asciidoc-py/asciidoc-py/issues/188. Given the specification process, this sort of change would have to go through that.
