### ISSUE TITLE
Labels lost after callouts

### ISSUE THREAD

**Issue by Tran6** [asciidoc-py/asciidoc-py2#121]
Label does not appearing after source code callouts

```
[source,xml]
----
  <myThing>
    <foo>foo</foo> <!--1-->
    <bar>bar</bar> <!--2-->
  </myThing>
----
<1> this is foo
<2> this is bar

myLabel:: this doesn't appear
```

**Comment by elextr** [comment]
Are you using the Asciidoc Python or Asciidoctor implementation (asked because the `<!--1-->` syntax is asciidoctor only)?  If its Asciidoctor probably best if you report the problem on its github https://github.com/asciidoctor/asciidoctor.

**Comment by Tran6** [comment]
Ah. You are correct, I am using the Asciidoctor implementation. I'll close the issue here.
Thank you, elextr, for the quick response!

**Comment by mojavelinux** [comment]
If I remember correctly, this was a bug in an older version of Asciidoctor. Can you test with Asciidoctor 1.5.6.1. If you can still reproduce, then report it here: https://github.com/asciidoctor/asciidoctor.
