### ISSUE TITLE
Support asciidoc/revealjs elements

### ISSUE THREAD

**Issue by chevdor** [asciidoc-py/asciidoc-py2#125]
Making slide decks using asciidoc is simply awesome and simplified by: https://asciidoctor.org/docs/asciidoctor-revealjs/

The generated slides can however not be modified. Importing the generated slides into google slides would allow benefiting from a new google slide feature: the ability to include (ie link) slides from other decks. That would allow mixing beautiful handcrafted slides with generated slides with code for instance.

There is however (please correct me if I am wrong) currently no way to convert asccidoc/revealjs slide decks to google slides. There is a nice tool doing just that but for Markdown: https://github.com/googlesamples/md2googleslides/

So the issue comes down to converting asciidoc/revealjs slides to markdown. 

A popular way seems to be https://tinyapps.org/blog/nix/201701240700_convert_asciidoc_to_markdown.html

This fails however in the case of asciidoc/revealjs documents with the following errors/warnings:
```
asciidoc: ERROR: solidity.adoc: line 4: illegal style name: %step
asciidoc: ERROR: solidity.adoc: line 10: illegal style name: NOTE.speaker
asciidoc: ERROR: solidity.adoc: line 21: illegal style name: .stretch
asciidoc: WARNING: slides.adoc: line 20: missing section: [background-color="green"]
asciidoc: WARNING: slides.adoc: line 7: missing section: [transition=zoom]
asciidoc: WARNING: slides.adoc: line 3: missing section: [background-iframe="https://www.yo..."]
```

Would there be a way to fix that or a workaround beside not using the offending styles?
`%step` and `NOTE.speaker` are rather critical for slides.

**Comment by aerostitch** [comment]
Hi,

The python 2 implementation of asciidoc (which is what this repo is about) is deprecated.
Please move your issue to the python 3 implementation at https://github.com/asciidoc/asciidoc-py3 if still relevant on that newer implementation and close this issue.

Thanks for your help,
Joseph

**Comment by mojavelinux** [comment]
First, this issue has to do with https://github.com/asciidoctor/asciidoctor-reveal.js, so it doesn't belong here.

I also don't think importing into Google Slides is the right way to go. I would recommend importing into slides.com, which should be possible once you use Asciidoctor Reveal.js to produce the deck.
