### ISSUE TITLE
How can I write include::preface.adoc[] in the document instead of including file?

### ISSUE THREAD

**Issue by blueray453** [asciidoc-py/asciidoc-py2#127]
I know to escape variables I can use \{qwe} and +++{qwe}+++

So far, I have tried to put "include::preface.adoc[]" inside code block.

----
include::preface.adoc[]
----

But still, "include::preface.adoc[]" is not showing as a line in my file.

Note: please go to edit this question to see what I was trying to say.

**Comment by elextr** [comment]
I can't try it at the moment, but maybe:

```
pass::[include::preface.adoc[]]
```

**Comment by mojavelinux** [comment]
Escape with a backslash (even inside a verbatim block)
