### ISSUE TITLE
toc levels don't display after level 6(:toclevels: property doesn't work) 

### ISSUE THREAD

**Issue by repomorphic** [asciidoc-py/asciidoc-py2#131]
Hello everyone. I am trying to create Toc that have more depth than 6. I tried following :
```
= Toc 
:idprefix:
:idseparator: -
:sectanchors:
:sectlinks:
:sectnumlevels: 10
:sectnums: 
:toc: macro
:toclevels: 10
:toc-title:

toc::[] 

== a

=== a

==== a

===== a

====== a
 
```

"======= a" didn't work even if I set up :toclevels: properly.
The sample asciidoc file :
https://gist.github.com/lostdinar2/289c29e93730af3a6f798b23b89d8c42

**Comment by mojavelinux** [comment]
That's because you've exceeded that maximum heading depth in AsciiDoc.

**Comment by elextr** [comment]
See http://asciidoc.org/userguide.html#X88 last entry.

**Comment by repomorphic** [comment]
Thanks elextr,
I have cloned asciidoc on my windows and  tried this(I am trying to adjust toc levels for ssample.adoc` file):
`python asciidoc.py -a toc -a toclevels=10 doc/ssample.adoc`

But I got following:
> File "asciidoc.py", line 101
> except KeyError, k: raise AttributeError, k

How to fix that?

**Comment by elextr** [comment]
@lostdinar2 as @mojavelinux and the link I posted said, Asciidoc levels do not go above 1..4.

**Comment by mojavelinux** [comment]
Asciidoctor allows them to go to 5 (which is 6 equal signs).

However, the error seems to be unrelated. Perhaps you are using Python 3?

**Comment by repomorphic** [comment]
Yes. I am using Python 3. Is there any way to increase heading depth? Why doesn't asciidoc allow to go to unlimited headings? 6 is a very small number for big documentations.

**Comment by elextr** [comment]
Asciidoc generates HTML or docbook, and those have only 6 levels and 4/5 levels respectively, so no there isn't a way of making more levels because there is no way of translating them to the output formats.

**Comment by lostdinar2** [comment]
Thanks for the reply. Other markup languages(markdown) have this restriction. I cannot create a big table of components. Any advice appreciated.
