### ISSUE TITLE
How can I adjust font-weight and font-size in asciidoc?

### ISSUE THREAD

**Issue by repomorphic** [asciidoc-py/asciidoc-py2#132]
Hello everyone. I am trying to adjust font-weight and font-size. Is there any asciidoc technique to adjust font-weight and font-size?
I have tried with HTML but it didn't work on the asciidoc file.
```
++++
<p style="font-weight:900;font-size:50px"> Sample </p>
++++
```

**Comment by elextr** [comment]
Asciidoc is a structural markup, not a presentational markup, so Asciidoc itself does not provide ways of setting styles, that is done by the backend, but all of them allow for entities marked with a role to be individually styled..  If you are generating HTML directly from Asciidoc you can use CSS for that, see http://asciidoc.org/userguide.html#X35

**Comment by repomorphic** [comment]
Thanks a lot. I tried this on asciidocfx editor which is converts asciidoc directly to HTML, it worked.
