### ISSUE TITLE
id reference isn't interpreted on asciidoc table

### ISSUE THREAD

**Issue by repomorphic** [asciidoc-py/asciidoc-py2#133]
I am trying to give id reference to my table elements like the following:

> [cols=2*,options=header]
> |====
> |[#pro-] pro-
> |in place of, on behalf of
> |====

It is interpreted the following:

> [cols=2*,options=header]
> |====
> |[#pro-] pro-
> |in place of, on behalf of
> |====

Instead of :
> [cols=2*,options=header]
> |====
> | pro-
> |in place of, on behalf of
> |====

**Comment by mojavelinux** [comment]
Please file Asciidoctor issues here: http://github.com/asciidoctor/asciidoctor

You have to use the "longhand" syntax to define an ID on a table cell.

```
|[[pro-]] pro-
|in place of, on behalf of
```
