### ISSUE TITLE
Generating man pages on macOS is extremely slow

### ISSUE THREAD

**Issue by martingalvan** [asciidoc-py/asciidoc-py2#134]
Hi all,

I'm trying to generate a man page on macOS 10.13.6 (High Sierra). I did:

`brew install asciidoc`

and then added the following to ~/.bash_profile:

`export XML_CATALOG_FILES=/user/local/etc/xml/catalog`

Now, when I try to do `a2x -f manpage mymanpage.1.txt`, the command takes a really long time to complete (3.5 min). The same command takes less than a second on Ubuntu 18.04. What am I doing wrong?

**Comment by elextr** [comment]
How long does it take to run `asciidoc -b docbook yourfile`?

**Comment by martingalvan** [comment]
Just tried it, takes less than a second.

**Comment by elextr** [comment]
So the problem is in the docbook to manpage xslt transform.  Thats a separate project, and I doubt anybody here can help you.

Alternatively you could try the [Asciidoctor](https://asciidoctor.org/) implementation of Asciidoc, it doesn't use docbook and xslt for manpages.

**Comment by martingalvan** [comment]
Alright, where should I report the issue instead?

**Comment by elextr** [comment]
[Here](https://github.com/docbook/) I guess, don't know what version you installed but I guess the issues for the appropriate version.

**Comment by martingalvan** [comment]
I don't see which repository should I report the issue to, so I think I'll just try asciidoctor instead. Thanks.
