### ISSUE TITLE
Quoted Text Chapted

### ISSUE THREAD

**Issue by GSebastian-Adil** [asciidoc-py/asciidoc-py2#136]

**Comment by GSebastian-Adil** [comment]
When I read the "Quoted Text" Chapter of "Asciidoc User Guide", I found some ponctuation in the description are not in place (and may be I am wrong), So I tried to rewrite this part to express my Opinion.
Thanks
[Quoted_Text.txt](https://github.com/asciidoc/asciidoc/files/2563216/Quoted_Text.txt)

**Comment by GSebastian-Adil** [comment]
Sorry I am new in github and I made mistakes in commenting

**Comment by MasterOdin** [comment]
Looks like the uploaded file is no longer available and so not sure what the suggested changes might have been. On a quick read through the section in question, did not notice any striking grammar issues.
