### ISSUE TITLE
Close all the PR and issues and disable new PR

### ISSUE THREAD

**Issue by aerostitch** [asciidoc-py/asciidoc-py2#137]
I think if we close all the PR and issues (saying that if you want to have something fixed, try it first with [asciidoc-py3](https://github.com/asciidoc/asciidoc-py3) or [asciidoctor](https://github.com/asciidoctor/asciidoctor) and then do a PR or open an issue on the relevant project) would send a clear message that this project is really EOL.
Plus that would push people to more supported implementations.
We could also completely disable the PR too for those who didn't see the message...

What do you think?

**Comment by aerostitch** [comment]
Maybe leave an issue open saying something like:
`This implementation of asciidoc is deprecated, please use asciidoctor or asciidoc-py3`
And in the description, put the link to both project.

**Comment by MasterOdin** [comment]
This project should probably just be marked as [Archived](https://help.github.com/en/articles/archiving-a-github-repository) which will make it impossible to write new issues/PRs/comments, but everything will look like it does right now (e.g. 28 issues, 20 PRs)

An example of an archived project: https://github.com/instructure/pdf-annotate.js/
