### ISSUE TITLE
How can I escape “/”  and "?" characters in asciidoc for inline anchors?

### ISSUE THREAD

**Issue by repomorphic** [asciidoc-py/asciidoc-py2#138]
Hi there.I am trying to write a program that automatically converts my website to asciidoc one document. But I have problem with asciidoc anchors.When I add "/" character into the anchor my anchors break down.

For example.The following asciidoc code works:
```
[[en-USdocs...]]
*Tutorials:*
------------
```
The following asciidoc code does not work due to the / character.

```
[[en-US/docs...]]
*Tutorials:*
------------
```
The following asciidoc code does not work due to the ? character.

```
[[en-USdocs?=...]]
*Tutorials:*
------------
```
Is there a way to escape this  “/”  and "?" characters to allow the anchor work properly?And also that would be awesome If I can  use special characters such as “/”  and "?" in inline anchors.

**Comment by elextr** [comment]
There is no way of getting illegal characters in the anchor id.

The anchor has to be a valid `ID` in all targets and so is limited to:
1.  alphanumerics
2. underscore (_)
3. colon(:) 
4. dot (.) and dash (-) anywhere other than the start of the ID

I suggest your conversion script replace the illegal characters with underscore.

**Comment by repomorphic** [comment]
Thanks. I have written a regex for replacing those illegal characters but I am wondering why these characters are illegal when I can use these characters in HTML id.

**Comment by elextr** [comment]
Because targets can still be html 4.
