### ISSUE TITLE
Automating Asciidoc into Github WIki Pages

### ISSUE THREAD

**Issue by sburkett** [asciidoc-py/asciidoc-py2#140]
Hello everyone! This is more of a question than a bug report.

I am trying to find a way to seamlessly integrate Asciidoc into our Github-hosted project wiki. Ideally, when we save a page on our Wiki, I'd like to automatically process and add a table of contents to the page, and possibly other formatting-related things as well. I am just really tired of manually generating the ToC and having to paste it into the wiki page manually. :)

I've browsed the Asciidoc manual, as well as performed some searches on Google, but I can't seem to find any guidance on this sort of thing. Is this possible? Github "actions" may do the trick, though I am not very familiar with them.

Thanks for any guidance or suggestions!

**Comment by MasterOdin** [comment]
Using GitHub action is probably the best way to go as you can set it up to only react on pushes to master. It looks like https://github.com/SwiftDocOrg/github-wiki-publish-action is an action to do this, especially once https://github.com/SwiftDocOrg/github-wiki-publish-action/pull/4 is merged as that'll allow you to sync more than just md files. You can use that branch (until it's merged and released on master) by doing `uses: SwiftDocOrg/github-wiki-publish-action@rsync` on your step.
