### ISSUE TITLE
Using the wrong python interpreter

### ISSUE THREAD

**Issue by evandrocoan** [asciidoc-py/asciidoc-py2#143]
Now Python 2.7 is deprecated, soon the default python interpreter will be Python 3 on newer linux distros. The problem here is that all python scripts define their headers with:
```
#!/usr/bin/env python
```

Which requires Python 2.7 and not Python 3. The problem I had is that on Windows with Cygwin, my default python interpreter is python 3.8 (python) and not python 2.7. Then, after installing this project, it attempted to run the scripts with Python 3.8 (which is the default python executable on my system).

I solved this problem locally by replacing all occurrences of:
```
#!/usr/bin/env python
# by
!/usr/bin/env python2
```

After changing this, and reinstalling the project, everything started working.

**Comment by elextr** [comment]
See https://github.com/asciidoc/asciidoc-py3
