### ISSUE TITLE
Any objections to archiving this repository?

### ISSUE THREAD

**Issue by elextr** [asciidoc-py/asciidoc-py2#145]
If no substantive reasons for not archiving are received in a short while this repository will be archived as it uses an end of life Python and is no longer maintained.

If anybody wants to do anything on this implementation they can still fork the repo on github.

**Comment by mojavelinux** [comment]
As soon as the pages are being served from asciidoc-py3, it seems reasonable to do so. Before that happens, I think it may be a good idea to update the description of the asciidoc/asciidoc-py3 repository so it reads more like the main repository and not a side project. Then the description of this repository should be updated so it's clear that it is the original source, but no longer the main source for AsciiDoc Python.

**Comment by MasterOdin** [comment]
`Python 2 toolchain for converting AsciiDoc text format to HTML, Docbook, and other formats. This version is unsupported in favor of https://github.com/asciidoc/asciidoc-py3 as Python 2 is EOL."

Then replace the 2 with a 3 and use the first sentence for the asciidoc-py3 repo? It's based on asciidoctor and I think it reads well and that enumerating what asciidoc is in the description is probably unnecessary.
