### ISSUE TITLE
Python2 syntax in backends list

### ISSUE THREAD

**Issue by Hexdump74** [asciidoc-py/asciidoc-py2#148]
Hi,

I have the version 9.0.2 from Archlinux official repos.

The command `asciidoc --backend list` outputs the following error :
```
File "/usr/bin/asciidoc", line 6025, in list
     for f in os.walk(d).next()[1]:
    AttributeError: 'generator' object has no attribute 'next'
```

Changing the line 6025 to `for f in next(os.walk(d))[1]:` seems to correct the problem.

**Comment by MasterOdin** [comment]
This affects the https://github.com/asciidoc/asciidoc-py3 repository (this repository is for the python2 version of asciidoc) and is fixed in https://github.com/asciidoc/asciidoc-py3/commit/42698ab6589f980010ad73c60669839de3c390da which will be part of 9.0.4 release.

**Comment by Hexdump74** [comment]
Oh, sorry to have messed up with the repos.
Thank you.
