### ISSUE TITLE
Provide the python api via pypi (pip)

### ISSUE THREAD

**Issue by jonblack** [asciidoc-py/asciidoc-py2#2]
The documentation for asciidoc says the following about using the python api:

> To use the API just drop the asciidocapi.py file into your application directory, import it and use the AsciiDocAPI class. The only requirement is that a compatible version of AsciiDoc is already installed — simple, no setuptools to run, no Eggs to install, no non-standard library dependencies.

This is quite cumbersome, especially when asciidoc is updated.

It would be nice to have the python api available via pypi and therefore installable with pip. This makes it a doddle to install into virtual environments and makes (automated) deployment much, much easier.

Note: I raised this issue based on the following issue I raised with the pelican project https://github.com/getpelican/pelican/issues/1212, which has support for asciidoc.

**Comment by elextr** [comment]
The intention is that _Pelican_ "drop the asciidocapi.py" file into their application, not leave it to their users.  It should install with Pelican if its needed.  That is why it is kept very small.

If Pelican wants to install the API from pypi then they should create a "pelican-asciidoc" package so they have complete control over the versions.

**Comment by jonblack** [comment]
As it's a requirement that asciidoc be installed when using the API, doesn't this introduce the risk of pelican (or any other project for that matter) providing a version of the API that isn't compatible with the user's installed version of asciidoc?

**Comment by elextr** [comment]
The API knows which versions of asciidoc it requires, and it checks the version it finds is acceptable (currently newer than 8.4.1).  It is generally intended that asciidoc remain backward compatible with the API (at least whilst its Python 2).

But the API itself is unversioned, the only way Pelican would know if it is compatible with the API is if it is included or pelican has control of the pypi package.

This possibly could be fixed, but needs some consideration of the details or it will restrict applications too much.

**Comment by jonblack** [comment]
If the python api is independent of asciidoc, my gut feeling is that it should be packaged separately as python-asciidoc. I'd also recommend versioning that API because if you ever have backwards incompatible changes, your users will thank you for it.

**Comment by aerostitch** [comment]
Hi,

The python 2 implementation of asciidoc (which is what this repo is about) is deprecated.
Please move your issue to the python 3 implementation at https://github.com/asciidoc/asciidoc-py3 if still relevant on that newer implementation and close this issue.

Thanks for your help,
Joseph

**Comment by MasterOdin** [comment]
The upcoming 10.0 release of AsciiDoc.py will be principally available via PyPI as a proper python package.
