### ISSUE TITLE
Dealing with line endings

### ISSUE THREAD

**Issue by edusantana** [asciidoc-py/asciidoc-py2#21]
I don't know if you have this problem, but [here goes the tip](https://help.github.com/articles/dealing-with-line-endings).

**Comment by elextr** [comment]
Why is this an issue?

**Comment by edusantana** [comment]
If you are having this problem it will be a reminder to do this later, since it's open here. If not, you can just close it.

In the future, if you preper to be contacted somewhere else, please just say where is the place. And we could put this information in the CONTRIBUTING file #16.

**Comment by elextr** [comment]
The idea for issues is to raise things that are actually related to the software, like bugs.  Github is only likely to be watched by programmers and technical user, not general users.  To simply discuss something please raise it on the ML where more people are likely to see it.

So if this is not causing an issue then it should not be raised here.

If it is causing an issue then please point out where and how.

**Comment by edusantana** [comment]
This issue is for programmers only. It will affect only people who does merges. Some times when some one change one line, `diff` will show that the entire file have changed, since the editor will replace the end of line for the entire file.

Since you are using git now and I had this problem in the past with others repositories I shared the solution here to get your life easier.

The users for asciidoc will not be affected. And this is not a problem for me, since I'm not doing merges.

**Comment by elextr** [comment]
I guess I wasn't clear, sorry.

This isn't a notice board, issues are not left open for information, they get closed.  So unless you are actually saying that Asciidoc has mixed line ends then there is no "issue" here and this will be closed.  

As you said, if someone wants to contribute a CONTRIBUTING thats where Hints like this should go.

**Comment by aerostitch** [comment]
Hi,

The python 2 implementation of asciidoc (which is what this repo is about) is deprecated.
Please move your issue to the python 3 implementation at https://github.com/asciidoc/asciidoc-py3 if still relevant on that newer implementation and close this issue.

Thanks for your help,
Joseph
