### ISSUE TITLE
Missing section in docbook backend

### ISSUE THREAD

**Issue by florentx** [asciidoc-py/asciidoc-py2#28]
While hardening the test suite (issue #27), I discovered that one test is complaining about `docbook45.conf` backend:

```
WARNING: missing macro section: [unfloat-blockmacro]
```

We chose to silence this warning in the test suite for the time being, until someone contribute a patch.

**Comment by elextr** [comment]
Docbook doesn't support unfloat as far as I know, so I don't see why it can't just be an empty macro on docbook.  Something like:

`[unfloat-blockmacro]`
`#nothing to see here`

should work.

**Comment by florentx** [comment]
works-for-me : https://travis-ci.org/florentx/asciidoc/builds/25250283

Thank you @elextr .
Closing in favor of PR #27
