### ISSUE TITLE
It's install.packages("ascii")

### ISSUE THREAD

**Issue by edusantana** [asciidoc-py/asciidoc-py2#34]
To install R ascii package:

The correct is: 

```
install.packages("ascii")
```

and not:

```
install.package("ascii")
```

**Comment by elextr** [comment]
What does this relate to?

**Comment by edusantana** [comment]
```
git grep -n "install.package"
```

> examples/website/index.txt:252:  'CRAN' (just run `install.package("ascii")` from R).  Brief

The line 252, of the file `examples/website/index.txt`, talk about R the some package `ascii` and the instruction about installing it is missing a `s`.

The correct is:

```
install.packages("ascii")
```

**Comment by edusantana** [comment]
@elextr sorry about this.

Since I'm with a few branchs here, I don't know how do a pull request fixing just this.

**Comment by elextr** [comment]
I just couldn't find it :)

Fixed in Git
