### ISSUE TITLE
Strange "implicit" wording in doco for a2x --fop option

### ISSUE THREAD

**Issue by apjanke** [asciidoc-py/asciidoc-py2#73]
Here's the `a2x` man page's description of `--fop`.

```
   --fop
       Use FOP to generate PDFs. The default behavior is to use dblatex(1). The --fop
       option is implicit if this option is used.
```

The last sentence about the option being implicit is confusing to me. This option implicitly enables itself? Is one of the option names here wrong? Looking at the a2x.py code, [it looks like `--fopt-opts` implicitly enables `--fop`](https://github.com/asciidoc/asciidoc/blob/f39afdacfb13d025a5d298c9c9dc5f6f211b7d44/a2x.py#L539-L540), so that sentence should be moved to the description for `--fop-opts`.

**Comment by elextr** [comment]
I'm sure this has been mentioned before, but maybe it was pre-github or no patch was produced.

The `--fop-opts` description already says "If this option is specified FOP is used to generate PDFs.".  So I think its just a case of replacing "this option" in the `--fop` description with "--fop-opts".

**Comment by rrthomas** [comment]
I just noticed this problem myself. Is there some reason it has not yet been fixed? @elextr's solution seems fine to me.

**Comment by elextr** [comment]
Basically nobody bothered to provide a pull request for it, fixed in https://github.com/asciidoc/asciidoc/commit/6896335a772e51e59766b6e11fe94b909f50d471

**Comment by rrthomas** [comment]
Thanks! In this case it would seem quicker to fix it yourself than read a pull request, otherwise I would happily have provided one. (Also, I'm waiting for my first pull request to be processed, because otherwise it does not seem worth providing more…)

**Comment by elextr** [comment]
I certainly didn't mean to imply that you yourself should have made a PR, but the issue has been there for almost two years.  Asciidoc has no full time contributors or maintainers so it doesn't matter how little effort it took to do, until somebody does it it won't happen.

I presume your other PR is #126 see new comment for how to proceed.

**Comment by mojavelinux** [comment]
> Asciidoc has no full time contributors or maintainers

To clarify for those who might get confused, that refers to AsciiDoc Python ;)

Asciidoctor is where development on AsciiDoc is being continued and is very much alive.

**Comment by elextr** [comment]
@mojavelinux yes, was entirely referring to Asciidoc Python, sorry :)

**Comment by mojavelinux** [comment]
No need to apologize. I know you know that. I just wanted to make sure we leave a trail of breadcrumbs for others following along.
