### ISSUE TITLE
Broken links on asciidoc.org

### ISSUE THREAD

**Issue by Caerbannog** [asciidoc-py/asciidoc-py2#79]
Most links to the documentation are broken at the following address:
http://asciidoc.org/#_overview_and_examples

Try to open the [AsciiDoc User Guide](http://asciidoc.org/asciidoc.css-embedded.html) for instance.

**Comment by neontapir** [comment]
Agreed, the example documents like the Sherlock Holmes ZIP are missing.

**Comment by sm0svx** [comment]
There is an active pull request that temporarily fix this while waiting for the correct solution (autogenerate rendered files from git asciidoc source).

https://github.com/asciidoc/asciidoc/pull/78

**Comment by Caerbannog** [comment]
Fixed online.

**Comment by lulalala** [comment]
The Sherlock Holmes example is gone again. If I want to see the source (the zip file) where can I see it? Can we upload that into this or a new repository?

**Comment by elextr** [comment]
Which sherlock holmes example?

**Comment by lulalala** [comment]
http://asciidoc.github.io/asciidoc/publishing-ebooks-with-asciidoc.html#X3

**Comment by elextr** [comment]
None of the example/book comtents seem to have ever been on the github based asciidoc.org, somebody would have to re-generate them, or better add them to the generator script.
