### ISSUE TITLE
Right To Left(RTL) support

### ISSUE THREAD

**Issue by omidp** [asciidoc-py/asciidoc-py2#85]
This issue is opened to discuss asciidoc RTL support. 

I created a sample [project](https://github.com/omidp/asciidoc_rtl) for testing and added a RTL lang corpus [here](https://github.com/asciidoc/asciidoc/pull/84)

I also need some more modification how can I change {docdate} or add a wrapper to it ? for example :

convertToJilaliDate({docdate});

**Comment by elextr** [comment]
The {eval: } system attribute can run any Python, so if Python provides the capability it can be run by eval.

**Comment by aerostitch** [comment]
Hi,

The python 2 implementation of asciidoc (which is what this repo is about) is deprecated.
Please move your issue to the python 3 implementation at https://github.com/asciidoc/asciidoc-py3 if still relevant on that newer implementation and close this issue.

Thanks for your help,
Joseph
