### ISSUE TITLE
Emphasis preceeding an em dash doesn't work

### ISSUE THREAD

**Issue by samwilson** [asciidoc-py/asciidoc-py2#86]
The following syntax doesn't work with `a2x`:

```
Lorem _ipsum_—lorem ipsum?
```

Instead, one must use double underscores:

```
Lorem __ipsum__—lorem ipsum?
```

Is this correct? I couldn't find anything in the documentation.

(I first raised this at gitenberg-dev/documentation/issues/15)

**Comment by elextr** [comment]
On 13 August 2015 at 09:02, Sam Wilson notifications@github.com wrote:

> The following syntax doesn't work with a2x:
> 
> Lorem _ipsum_—lorem ipsum?
> 
> Instead, one must use double underscores:
> 
> Lorem **ipsum**—lorem ipsum?
> 
> Is this correct? I couldn't find anything in the documentation.

​Yes, see http://asciidoc.org/userguide.html#X51 10.1.2 constrained quotes
must be bounded by whitespace.

Cheers
Lex​

**Comment by samwilson** [comment]
Oh cool — and thanks for the quick reply!

That makes sense.

Is there a list somewhere of the ["commonly adjoining punctuation characters"](http://asciidoc.org/userguide.html#_constrained_quotes)? I'm guessing it's something like apostrophe, comma, and full stop?

**Comment by elextr** [comment]
To be precise before the opening quotes it is the Python 2 regular expression in Unicode mode `(^|[^\w:;])` and after the closing quotes `\W` or end of line.

In imprecise English that is: before the quotes must be `^` or anything but `:`, `;`, `0-9`, `_` or any Unicode alphabetic and after the quotes end of line or anything but `0-9`, `_` or any Unicode alphabetic.

Which whilst it does include "commonly adjoining punctuation characters" its also rather more.
