### ISSUE TITLE
asciidoc.org/INSTALL.html still references Google Code mercurial repo

### ISSUE THREAD

**Issue by aarongable** [asciidoc-py/asciidoc-py2#99]
The [installation documentation](http://asciidoc.org/INSTALL.html) still contains the following instructions:

> The AsciiDoc Mercurial repository is hosted by Google Code. To browse the repository go to http://code.google.com/p/asciidoc/source/browse/

and

> $ hg clone -r 8.6.9 https://asciidoc.googlecode.com/hg/ asciidoc-8.6.9

These are out-of-date now that this appears to be the canonical repository, and the latter is simply broken now that Google Code has shut down its source code hosting.

**Comment by mojavelinux** [comment]
The site just needs to be published. It's correct in the git repo.

**Comment by tanriol** [comment]
The site is still out of date.

**Comment by mojavelinux** [comment]
I fixed it manually. http://asciidoc.org/INSTALL.html
